Fix the gulp build for node version 8
On node v8+ I'm seeing the build failure below, which
appears to be due to now-deprecated javascript code
that is contained within require-dir, which vector is
importing via gulp-git.

/source/git/vector/node_modules/require-dir/index.js:93
            if (!require.extensions.hasOwnProperty(ext)) {
                                    ^

TypeError: require.extensions.hasOwnProperty is not a function
    at requireDir (/source/git/vector/node_modules/require-dir/index.js:93:37)
    at Object.<anonymous> (/source/git/vector/node_modules/gulp-git/index.js:4:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/source/git/vector/gulp/scripts.js:7:11)